# VabHub 媒体库配置文件
# 基于MoviePilot基准优化的媒体管理配置

# 媒体库扫描配置
media_library:
  # 扫描路径配置
  scan_paths:
    - path: "/media/movies"
      type: "movie"
      enabled: true
    - path: "/media/tv"
      type: "tv"
      enabled: true
    - path: "/media/anime"
      type: "anime"
      enabled: true
    - path: "/media/music"
      type: "music"
      enabled: true

  # 扫描设置
  scan_settings:
    interval: 3600  # 扫描间隔（秒）
    recursive: true
    follow_symlinks: false
    exclude_patterns:
      - "*.nfo"
      - "*.txt"
      - "sample/*"
      - "extras/*"

  # 文件识别设置
  recognition:
    movie_patterns:
      - "{title} ({year})"
      - "{title} {year}"
    tv_patterns:
      - "{title} S{season:02d}E{episode:02d}"
      - "{title} Season {season} Episode {episode}"

# 元数据刮削配置
metadata:
  # TMDB配置
  tmdb:
    api_key: "your_tmdb_api_key"
    language: "zh-CN"
    include_adult: false
    timeout: 30

  # 豆瓣配置
  douban:
    api_key: "your_douban_api_key"
    timeout: 30

  # 刮削优先级
  scrapers:
    - "tmdb"
    - "douban"
    - "fanart"

  # 元数据保存设置
  save_settings:
    nfo_files: true
    poster_files: true
    fanart_files: true
    actor_images: true

# 下载器配置
downloader:
  # qBittorrent配置
  qbittorrent:
    host: "localhost"
    port: 8080
    username: "admin"
    password: "adminadmin"
    ssl: false

  # Transmission配置
  transmission:
    host: "localhost"
    port: 9091
    username: "transmission"
    password: "transmission"
    ssl: false

  # 下载设置
  download_settings:
    save_path: "/downloads"
    category: "vabhub"
    paused: false
    sequential: false
    auto_management: true

# 订阅系统配置
subscription:
  # RSS订阅源
  rss_sources:
    - name: "M-Team"
      url: "https://tp.m-team.cc/rss.php"
      type: "torrent"
      enabled: true
    - name: "PTer"
      url: "https://pterclub.com/rss.php"
      type: "torrent"
      enabled: true

  # 订阅规则
  rules:
    # 电影规则
    movie_rules:
      - name: "4K电影订阅"
        enabled: true
        quality: "2160p"
        codec: ["H.265", "HEVC"]
        size_min: "10GB"
        size_max: "50GB"

    # 电视剧规则
    tv_rules:
      - name: "高清电视剧订阅"
        enabled: true
        quality: "1080p"
        codec: ["H.264"]
        season: "latest"

  # 自动化设置
  automation:
    check_interval: 300  # 检查间隔（秒）
    max_downloads: 5     # 最大同时下载数
    remove_finished: true # 完成后删除任务

# 用户界面配置
ui:
  # 主题设置
  theme:
    primary: "#1976d2"
    secondary: "#424242"
    accent: "#82b1ff"
    error: "#ff5252"
    info: "#2196f3"
    success: "#4caf50"
    warning: "#ffc107"

  # 布局设置
  layout:
    dark_mode: false
    sidebar_width: 256
    card_elevation: 2
    rounded_corners: true

  # 显示设置
  display:
    items_per_page: 20
    grid_columns: 4
    show_thumbnails: true
    show_ratings: true

# 通知配置
notification:
  # Webhook通知
  webhook:
    enabled: false
    url: ""
    events:
      - "download_started"
      - "download_completed"
      - "subscription_matched"

  # 邮件通知
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    to_address: ""

# 系统配置
system:
  # 日志设置
  logging:
    level: "INFO"
    file: "/var/log/vabhub/vabhub.log"
    max_size: "100MB"
    backup_count: 5

  # 数据库设置
  database:
    type: "sqlite"
    path: "/var/lib/vabhub/vabhub.db"
    timeout: 30

  # 性能设置
  performance:
    max_workers: 10
    thread_pool_size: 20
    cache_size: "1GB"
    cache_ttl: 3600