# 音乐订阅配置文件
# 基于ptmusic-sub v2功能集成的配置模板

# 日志配置
log_level: INFO

# 运行时配置
runtime:
  out_dir: "/var/vabhub/music/subscriptions"
  state_db: "/var/vabhub/music/state/subscriptions.db"
  cache_dir: "/var/vabhub/music/cache"

# 下载器配置
downloader:
  type: qbittorrent
  base_url: "http://localhost:8080"
  username: "admin"
  password: "adminadmin"
  timeout: 30

# 元数据配置
metadata:
  itunes:
    enabled: true
    timeout: 30
    cover_size: 600
  
  musicbrainz:
    enabled: true
    timeout: 30
    user_agent: "VabHub-MusicManager/2.0.0"
  
  lyrics:
    enabled: true
    provider: "lrclib"
    timeout: 30

# 订阅配置
subscriptions:
  # 热门艺人订阅
  taylor_swift:
    enabled: true
    mode: "torznab"
    endpoints:
      - "http://jackett:9117/api/v2.0/indexers/all/results/torznab/api?apikey=YOUR_API_KEY"
    query: "Taylor Swift"
    category: 3000
    interval: 3600  # 1小时
    auto_add: false
    max_add: 3
    save_path: "/downloads/music"
    qb_category: "music"
    rules:
      include_keywords: ["FLAC", "WEB", "ALAC"]
      exclude_keywords: ["Pack", "合集", "Karaoke", "Instrumental"]
      require_quality: ["FLAC", "ALAC"]
      reject_pack: true
      prefer_keywords: ["WEB", "FLAC", "24bit"]

  # 榜单订阅
  charts_hot_50:
    enabled: true
    mode: "torznab"
    endpoints:
      - "http://jackett:9117/api/v2.0/indexers/all/results/torznab/api?apikey=YOUR_API_KEY"
    query: "charts"
    category: 3000
    interval: 7200  # 2小时
    auto_add: false
    max_add: 5
    save_path: "/downloads/music"
    rules:
      include_keywords: ["Billboard", "Hot", "Top"]
      exclude_keywords: ["Pack", "合集"]
      require_quality: ["FLAC", "ALAC"]

# 榜单订阅生成配置
chart_subscriptions:
  enabled: true
  chart_sources:
    - type: "apple_music"
      path: "/var/vabhub/charts/apple_music.jsonl"
      weight: 1.0
    - type: "spotify"
      path: "/var/vabhub/charts/spotify.jsonl"
      weight: 0.8
  
  generation:
    top_artists: 50
    update_interval: 86400  # 24小时
    auto_enable: true

# 标签嵌入配置
tag_embedding:
  enabled: true
  formats: ["mp3", "flac"]
  cover_quality: "high"
  backup_original: true
  
  # 嵌入选项
  embed_cover: true
  embed_lyrics: true
  embed_musicbrainz: true

# 通知配置
notifications:
  enabled: true
  providers:
    - type: "webhook"
      url: "http://localhost:8080/api/notifications"
      events: ["subscription_completed", "download_started", "metadata_enriched"]
    
    - type: "email"
      smtp_server: "smtp.example.com"
      port: 587
      username: "noreply@example.com"
      password: "password"
      to: ["user@example.com"]
      events: ["subscription_error", "download_failed"]

# 性能配置
performance:
  max_concurrent_searches: 5
  search_timeout: 30
  download_timeout: 300
  cache_ttl: 3600

# 高级配置
advanced:
  # 去重配置
  deduplication:
    enabled: true
    method: "title_size"  # 基于标题和文件大小去重
    
  # 重试配置
  retry:
    max_attempts: 3
    backoff_factor: 2
    
  # 代理配置
  proxy:
    enabled: false
    http: "http://proxy:8080"
    https: "https://proxy:8080"