name: Release VabHub-Resources

on:
  push:
    tags:
      - 'v*'

# 设置权限
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate configuration files
      run: |
        # Validate YAML files
        if [ -d "config/" ] && [ "$(ls -A config/)" ]; then
          find config/ -name "*.yaml" -exec python -c "import yaml; yaml.safe_load(open('{}'))" \;
          find config/ -name "*.yml" -exec python -c "import yaml; yaml.safe_load(open('{}'))" \;
        fi
        
        # Validate JSON files
        find . -name "*.json" -exec python -c "import json; json.load(open('{}'))" \; 2>/dev/null || echo "No JSON files found"

    - name: Create release package
      run: |
        mkdir -p dist
        cp -r config/ dist/
        cp -r data/ dist/
        cp -r scripts/ dist/
        cp -r kubernetes/ dist/
        cp README.md dist/
        cp CHANGELOG.md dist/
        
        # 创建压缩包
        cd dist
        zip -r "../vabhub-resources-${GITHUB_REF_NAME}.zip" .
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: vabhub-resources-*.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        # 构建Docker镜像
        docker build -t ghcr.io/strmforge/vabhub-resources:${{ github.ref_name }} .
        docker build -t ghcr.io/strmforge/vabhub-resources:latest .
        
        # 登录GitHub Packages
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
        # 推送镜像到GitHub Packages
        docker push ghcr.io/strmforge/vabhub-resources:${{ github.ref_name }}
        docker push ghcr.io/strmforge/vabhub-resources:latest